sudo: required
dist: trusty
language: cpp
 
# whitelist
branches:
  only:
    - master

install:
  - sudo apt-get install libsdl2-dev -y
  - sudo apt-get install libsdl2-image-dev -y
  - sudo apt-get install libsdl2-mixer-dev -y
  - sudo apt-get install libsdl2-ttf-dev -y
  - sudo apt-get install zlib1g-dev -y 
  - sudo apt-get install make -y
  - sudo apt-get install cmake -y
  - sudo apt-get install clang -y
  - sudo apt-get install build-essential -y

compiler:
  - clang++

script:
  - make
